version: '3'
services:
  mongodb-app:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb:/data/db

  backend:
    container_name: backend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    links:
      - mongodb-app

volumes:
  mongodb:
