require('dotenv').config({ path: '.env' })

const {
  MONGODB_URI,
  PORT,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  EMAIL_USER,
  EMAIL_PASS,
  ACCESS_TOKEN_JWT_SECRET,
  REFRESH_TOKEN_JWT_SECRET,
  ACCESS_TOKEN_JWT_EXPIRATION,
  ACCESS_TOKEN_JWT_REFRESH_EXPIRATION,
  APP_HOSTNAME
} = process.env

module.exports = {
  MONGODB_URI,
  PORT,
  EMAIL_USER,
  EMAIL_PASS,
  ACCESS_TOKEN_JWT_SECRET,
  REFRESH_TOKEN_JWT_SECRET,
  ACCESS_TOKEN_JWT_EXPIRATION,
  ACCESS_TOKEN_JWT_REFRESH_EXPIRATION,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  APP_HOSTNAME
}
